# Generated by Django 5.1.1 on 2024-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='op_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
