# Generated by Django 5.1.1 on 2024-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_appointment_description_appointment_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('9AM-10AM', '9AM-10AM'), ('10AM-11AM', '10AM-11AM'), ('11AM-12PM', '11AM-12PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM')], max_length=20, null=True),
        ),
    ]
