# Generated by Django 5.1.1 on 2024-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registration_source',
            field=models.CharField(choices=[('admin', 'Admin'), ('external', 'External')], default='external', max_length=20),
        ),
    ]
